### ISSUE TITLE
Add temp invulnerabilty on victory

### ISSUE THREAD

**Issue by HoboMechanistic** [ribbybibby/Grimm-Journey#30]
Sometimes when cutting it close and you finish the level, you can still loose if one of your characters die. This may be because the level transition takes a while to trigger.

A way to fix this would be to make both characters invulnerable on victory. We shouldn't need to reset this as the next level is a separate scene. Maybe just to be safe on start set invuln to false.

**Comment by ribbybibby** [comment]
Assigning to me. This is how I will approach it:

1. Like Rob says, add an 'invuln' variable (to false) on Start inside the Receiver script
2. Add an 'if' to the ApplyDamage method that checks that invuln is false
3. Have the victory object change the 'invuln' variable inside BBW and LRRH to true OnTriggerEnter and to false OnTriggerExit

**Comment by ribbybibby** [comment]
Fixed in 31115c30f30d91ff1e3b1070d9feebcee873b28d

I've implemented the above. 

The only thing to be mindful of is that this will make either character invulnerable when they sit in the Victory alone as well, but I kind of like that. If we decide to change this then we'd just need to add some slightly more in-depth conditional logic to the OnTriggerEnter and OnTriggerExit methods.

**Comment by HoboMechanistic** [comment]
I kind of like this as well :D Could result in scenarios where the player has to leave the safety to help the other player.

"Come save me! I can't jump!"
"No, screw you, I'm safe here!"
