### ISSUE TITLE
Player 2 BBW can't attack

### ISSUE THREAD

**Issue by HoboMechanistic** [ribbybibby/Grimm-Journey#36]
After a character swap, if player 2 is the BBW. They can't atack using the UOP keys.

**Comment by ribbybibby** [comment]
Assigning to me for a bit seen as RDJ is doing Uni stuff. I'll try and see why this is happening seen as I implemented the flaky ass switching mechanic.

**Comment by ribbybibby** [comment]
Fixed in 9eb447744c8d003c6ca840df66bc9bad9afe816c

This was happening because we had an if statement enclosing each attack that checked that the game object was in the player 1 layer. Therefore, it would ignore all attack input from player 2. I shuffled this around by only checking for the player 1 layer in cases where the pad was used.

This produces some pretty long and hard to understand conditional statements but I have commented them heavily to try and remove any confusion. In future, if we want to deviate P1 and P2 attacks from each other, we could split these into two distinct 'if' trees inside the script for individual management.
