### ISSUE TITLE
Check that Xbox 360 controls work for PC

### ISSUE THREAD

**Issue by ribbybibby** [ribbybibby/Grimm-Journey#4]
We had a lot of complaints about the controls in the game. We should double check that the Pad controls work, primarily for PC, because Leftfield runs the games on PC.

Passing this to RDJ because he implemented the pad stuff. After that, as a stretch, I can try and add Mac/Linux functionality.

**Comment by HoboMechanistic** [comment]
Another note - Get the pause menu logic working with pad as well.

**Comment by HoboMechanistic** [comment]
Jump2 in the input manager is what was causing the double jump bug. Really weird since it looked like it was set up fine. Since I'm cleaning this up I disabled the jump for player 2 on pads. Just for now.

Double jump entry - This was because set as according to the internets is good practice to use the input manager to bind keys rather than hardcode them via GetKey. This allows the users to rebind keys using that front panel Unity provides. But I disabled that since many many people don't like it. We also do hardcode it for now so I removed the duplicate keyboard jump since we dont need it just yet. The game isn't that complex in terms of movement, so I don't really feel its worth investing time into this atm. T many other things to do first.

**Comment by HoboMechanistic** [comment]
Lol this is such a blanket bug! (orton)

With regards to the Jump2 (both players jumping with one pad) I fixed this properly now. The input type was set to broad for player two. This meant that it was accepting player 1 input for some reason. That's one bug down. Many more to go.

I'm gonna start bugging pad bugs separately now. Please also see bug #33
