### ISSUE TITLE
[Audio] Play bwwarp sound when darkness appears on-screen

### ISSUE THREAD

**Issue by ribbybibby** [ribbybibby/Grimm-Journey#58]
We ripped the bwwarp sound from the BG track in #23, now we need to code in an event that will trigger it when the darkness comes on screen. For levels where we use the track it was ripped from... I'm not sure, we come up with a clever solution.

**Comment by HoboMechanistic** [comment]
Since I'm slowly putting in the narration stuff I dont mind doing this. Shouldn't be to hard to add the sound effect in on darkness spawn (read rise up).

As for the music track we could edit it. Deleting the bwap and then fading out and back in. For example before bwap plays we fade out to silence, then the deleted section gets played, then we fade back in. Can make a demo to use for testing to see how this sounds in-game.

**Comment by HoboMechanistic** [comment]
Added the bwap sound to the darkness and made it play when the darkness triggers a 'Ground' tagged collision box. Notes to self:

Add bool so that it doesn't keep playing when hitting other Grounds (should only place once)
Resize the collsion box on the darkness since it's triggering about 2 seconds to late.

**Comment by HoboMechanistic** [comment]
Added the bool (more for completeness sake) since we only tag the Floor prefab as Ground. But thinking ahead incase we tag anything else with Ground in the future for some reason. This is fixed now, the only thing that remains is maybe tweaking the playBwap() method. But with the new camera panning I dont think we need to fine tune it really.
