### ISSUE TITLE
[Project] Upgrade to Unity 5; fix issues

### ISSUE THREAD

**Issue by ribbybibby** [ribbybibby/Grimm-Journey#73]
I've upgraded my local copy to Unity 5 and there are a few issues that will need to be resolved.

That I've found so far:
- Spine causing a compiler error (FIXED - by commenting out offending line)

- Some levels go absolutely mental, with the whole scene doubling, wrapping into itself and disappearing off screen (possibly related to error 'Non-convex MeshCollider with non kinematic Rigidbody is no longer supported in Unity 5')

- Various unsupported bits of code that will need to be updated for U5

**Comment by HoboMechanistic** [comment]
Nice one dude, I've done the same on Thursday (commenting out the spine stuff to get the build compiling). Not gotten much further than that. I'll have a look at the spine runtimes and see if I can find an updated one. I have a hunch the definition they added was a quick addition rather than a proper fix (If Unity 5 then blah).  Apart from that I'll hold off making any serious changes so that we dont end up doing the same thing.

**Comment by ribbybibby** [comment]
Cleared up all the errors I could see in 59cfcd577027c759de5cfcec03731eaa68cf8b91.

This included commenting out the spine stuff, which might need a proper fix, so leaving open for now.

**Comment by HoboMechanistic** [comment]
I found a solution to the spine stuff, the definitions may need to be refactored to support the newer unity, there's a simple fix to get the build compiling for now, which I'll commit tonight. However I want to make sure that we don't run into this problem further down the line.

**Comment by HoboMechanistic** [comment]
This should be fixed now.
